---
- name: Deploy Docker container
  hosts: localhost
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        tag: latest
        state: present

    - name: Run Docker container
      docker_container:
        name: myapp_container
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "8081:8080"
